### PR TITLE
Upgrade pip & nbrsessionproxy versions

### PR DESCRIPTION
**Pull request by yuvipanda**
This gives us shiny support as well

### CODE REVIEW

**Comment by yuvipanda** [comment]
I'm also making an official example using this here: https://github.com/binder-examples/rocker

This is probably faster than using install.R

**Comment by yuvipanda** [comment]
The test failed due to a github rate limit. Would be great if someone could restart it.

**Comment by cboettig** [comment]
good times trying to get encrypted token passed in as docker build argument.  But this looks good anyway, so will merge as is!

**Comment by yuvipanda** [comment]
Thanks, @cboettig

**Pull request merged**
